version: '2'

services:
  ibsmiling:
    build: .
    container_name: ibsmiling
    restart: unless-stopped
    #ports:
    # - "8080:80"
    expose:
     - "80"
    environment:
     - VIRTUAL_HOST=ibsmiling.com,www.ibsmiling.com
     - LETSENCRYPT_HOST=ibsmiling.com,www.ibsmiling.com
    networks:
     - reverse-proxy

networks:
  reverse-proxy:
    external:
      name: proxy_reverse-proxy
